// Code generated by go-bindata.
// sources:
// migrations/0001-CreateUserTable.sql
// DO NOT EDIT!

package migrations

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _migrations0001CreateusertableSql = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x84\xce\xc1\x6e\xd3\x30\x1c\x06\xf0\xbb\x9f\xe2\xd3\x4e\xad\x84\x6b\x98\x34\x0e\x1d\x42\x94\xcd\x05\x8b\x34\x45\xad\xa3\x6d\x5c\x90\xe7\xfc\x97\x58\x4b\x62\xcb\x76\xa8\xf6\x48\xbc\x06\x4f\x86\xb2\x8e\x5e\x38\xec\x68\xff\xbf\xdf\xa7\x8f\x73\xf4\x4f\x29\x1b\xfb\xc8\xad\x1f\x72\xf4\x5d\x47\x11\x26\x38\xc6\x39\xda\x9c\x43\x5a\x0a\xd1\xb8\xdc\x8e\xf7\x0b\xeb\x7b\x91\x7d\x78\x88\x44\x8d\xe9\x29\x89\xff\x25\xe3\x7c\x82\x85\xb3\x34\x24\xaa\x31\x0e\x35\x45\xe4\x96\xb0\x51\x1a\xdd\xf1\x7b\xf9\xaf\x7b\x29\xc4\xe1\x70\x58\xf8\x40\x43\xf2\x63\xb4\xb4\xf0\xb1\x11\x2f\xa9\x24\x7a\x97\xf9\xcb\x63\x12\x57\x3e\x3c\x45\xd7\xb4\x19\x7f\x7e\xe3\xfc\xed\xbb\xf7\xd0\x3e\x60\x1d\x89\xf0\x65\x9a\x83\x0f\xf7\xc6\x3e\xd2\x50\x7f\xca\x0f\x8d\xf5\xd3\xdc\x8f\x8c\x5d\xed\xe4\x4a\x4b\xc8\x5b\x2d\xcb\xbd\xda\x96\x50\x6b\x94\x5b\x0d\x79\xab\xf6\x7a\x8f\xb3\x71\x74\x35\xf7\x29\x85\xb3\xcb\x53\x58\xaf\x3e\x17\x12\x63\xa2\x98\x30\x63\x00\xe0\x6a\x54\x95\xba\xc6\xf7\x9d\xda\xac\x76\x77\xf8\x26\xef\xde\x3c\x1f\xa8\x37\xae\xc3\x2f\x13\x6d\x6b\xe2\xec\xfc\xe2\x62\xfe\xdc\x5e\x56\x45\x71\x0c\xd8\x48\x26\x53\xfd\xd3\x64\x64\xd7\x53\xca\xa6\x0f\xb8\x51\xfa\x2b\xb4\xda\x48\xfc\xd8\x96\xf2\x24\x70\x2d\xd7\xab\xaa\xd0\x28\xb7\x37\xb3\xf9\xd1\x8f\xa1\x7e\xdd\x57\x45\xc1\xe6\x97\x8c\xfd\x0d\x00\x00\xff\xff\x6a\x34\x43\x05\xce\x01\x00\x00")

func migrations0001CreateusertableSqlBytes() ([]byte, error) {
	return bindataRead(
		_migrations0001CreateusertableSql,
		"migrations/0001-CreateUserTable.sql",
	)
}

func migrations0001CreateusertableSql() (*asset, error) {
	bytes, err := migrations0001CreateusertableSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "migrations/0001-CreateUserTable.sql", size: 462, mode: os.FileMode(420), modTime: time.Unix(1491249164, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"migrations/0001-CreateUserTable.sql": migrations0001CreateusertableSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"migrations": &bintree{nil, map[string]*bintree{
		"0001-CreateUserTable.sql": &bintree{migrations0001CreateusertableSql, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
